// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using casbin_poc.Data;

#nullable disable

namespace casbin_poc.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260901132051_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.11");

            modelBuilder.Entity("Casbin.Persist.Adapter.EFCore.Entities.EFCorePersistPolicy<System.Guid>", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("Type")
                        .HasColumnType("TEXT")
                        .HasColumnName("ptype");

                    b.Property<string>("Value1")
                        .HasColumnType("TEXT")
                        .HasColumnName("v0");

                    b.Property<string>("Value10")
                        .HasColumnType("TEXT")
                        .HasColumnName("v9");

                    b.Property<string>("Value11")
                        .HasColumnType("TEXT")
                        .HasColumnName("v10");

                    b.Property<string>("Value12")
                        .HasColumnType("TEXT")
                        .HasColumnName("v11");

                    b.Property<string>("Value13")
                        .HasColumnType("TEXT")
                        .HasColumnName("v12");

                    b.Property<string>("Value14")
                        .HasColumnType("TEXT")
                        .HasColumnName("v13");

                    b.Property<string>("Value2")
                        .HasColumnType("TEXT")
                        .HasColumnName("v1");

                    b.Property<string>("Value3")
                        .HasColumnType("TEXT")
                        .HasColumnName("v2");

                    b.Property<string>("Value4")
                        .HasColumnType("TEXT")
                        .HasColumnName("v3");

                    b.Property<string>("Value5")
                        .HasColumnType("TEXT")
                        .HasColumnName("v4");

                    b.Property<string>("Value6")
                        .HasColumnType("TEXT")
                        .HasColumnName("v5");

                    b.Property<string>("Value7")
                        .HasColumnType("TEXT")
                        .HasColumnName("v6");

                    b.Property<string>("Value8")
                        .HasColumnType("TEXT")
                        .HasColumnName("v7");

                    b.Property<string>("Value9")
                        .HasColumnType("TEXT")
                        .HasColumnName("v8");

                    b.HasKey("Id");

                    b.HasIndex("Type");

                    b.HasIndex("Value1");

                    b.HasIndex("Value2");

                    b.HasIndex("Value3");

                    b.HasIndex("Value4");

                    b.HasIndex("Value5");

                    b.HasIndex("Value6");

                    b.ToTable("casbin_rule", (string)null);
                });

            modelBuilder.Entity("casbin_poc.Models.Tasks", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DueDate")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Timestamp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId");

                    b.ToTable("Tasks");
                });

            modelBuilder.Entity("casbin_poc.Models.Users", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Auth0Sub")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Timestamp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("casbin_poc.Models.Tasks", b =>
                {
                    b.HasOne("casbin_poc.Models.Users", "Owner")
                        .WithMany()
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Owner");
                });
#pragma warning restore 612, 618
        }
    }
}
